routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* 
	to override the show method to accept slug and not question for more SEO friendly
*/
Route::resource('questions', 'QuestionsController')->except('show'); // will exclude 'show'
Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');

// Route::post('/questions/{questions}/answers', 'AnswerController@store')->name('answers.store');
// Route::resource('questions.answers', 'AnswersController')->(['store', 'edit', 'update', 'destroy']);

Route::resource('questions.answers', 'AnswersController')->except(['create', 'show ']);

Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use VotableTrait;
    
	protected $fillable = ['title', 'body'];

    protected $appends = ['created_date', 'is_favorited', 'favorites_count', 'body_html'];

    public function user() {
    	return $this->belongsTo(User::class); // A question belongs to a user // DEMONSTRATES ONE TO MANY RELATIONSHIP
    }

    public function setTitleAttribute($value) 
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
        
    }

    public function getUrlAttribute() 
    {
    	return route("questions.show", $this->slug);
    }

    public function getCreatedDateAttribute() 
    {
    	return $this->created_at->diffForHumans(); //makes the date in "3 days ago format"
    }

    public function getStatusAttribute() 
    {
        if ( $this->answers_count > 0 ) {
            if ( $this->best_answer_id ) {
                return "answered-accepted";
            }
            return "answered";
        } else {
            return "unanswered";
        }
    }

    public function getBodyHtmlAttribute()
    {
        return clean( $this->bodyHtml() );
    }

    public function answers() 
    {
        return $this->hasMany(Answer::class);
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    // $question = Question::find(1); //finds the question that belongs to user with ID 1, 
    // $question->user->email  (gets the user email)

    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }

    public function isFavorited()
    {
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }

    public function getFavoritesCountAttribute()
    {
        return $this->favorites()->count();
    }  

    public function getExcerptAttribute()
    {
        return clean ( $this->excerpt(250) );
    }

    public function excerpt($length) 
    {
        return str_limit( strip_tags( $this->body_html ) , $length);
    }

    private function bodyHtml()
    {
        return \Parsedown::instance()->text($this->body);
    }  

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\AskQuestionRequest;

class QuestionsController extends Controller
{
    public function __construct() {
        $this->middleware('auth', ['except' => ['index', 'show', ]]); //THIS WILL LIMIT ALL THE PAGES except the slug of the pages included in the parameter
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::with('user')->latest()->paginate(5);
        
        // THE COMMENTED CODES WILL DISPLAY THE DETAILS OF THE QUERY
        // \DB::enableQueryLog(); // debugging purposes
        // view('questions.index', compact('questions'))->render(); // debugging purposes
        // dd(\DB::getQueryLog()); // debugging purposes


        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();

        return view('questions.create', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
        $request->user()->questions()->create($request->all()); // $request->only('title', 'body')  //OR IF YOU WANT TITLE ONLY

        return redirect()->route('questions.index')->with('success', "Your question has been submitted"); 
        // or redirect('/questions')->with('success', "Your question has been updated "); TO REDIRECT ONLY
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views'); //INCREMENT VIEWS FIELD BY 1

        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        // if (\Gate::allows('update-question', $question)) {    
        //     return view("questions.edit", compact('question'));
        // }
        // abort(403, "Access Denied");

        // negated story 
        if (\Gate::denies('update-question', $question)) {       
            abort(403, "Access Denied");
        }
        return view("questions.edit", compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        if (\Gate::denies('update-question', $question)) {       
            abort(403, "Access Denied");
        }

        // return view("questions.edit", compact('question')); // NOT NEEDED THIS

        $question->update($request->only('title', 'body'));

        if ($request->expectsJson()) {
            return response()->json([
                'message'   => "Your question has been updated.",
                'body_html' => $question->body
            ]);
        }

        return redirect()->route('questions.index')->with('success', "Your question has been updated.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        if (\Gate::denies('delete-question', $question)) {       
            abort(403, "Access Denied");
        }
        // return view("questions.edit", compact('question'));
        $question->delete();

        if ( request()->expectsJson() ) {

            return response()->json([
                'message'   => "Your question has been deleted."
            ]);

        }

        return redirect()->route('questions.index')->with('success', "Your question has been deleted.");
    }
}

resources/views/questions/_form.blade.php
 @csrf
<div class="form-group">
    <label for="question-title">Question Title</label>
    <input type="text" name="title" id="question-title" value="{{ old('title', $question->title) }}" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">

    @if ( $errors->has('title') )
        <div class="invalid-feedback">
            <strong>{{ $errors->first('title') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <label for="question-body">Explain your Question</label>
    <textarea name="body" id="question-body" rows="5" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">
        {{ old('body', $question->body) }}
    </textarea>

     @if ( $errors->has('title') )
        <div class="invalid-feedback">
            <strong>{{ $errors->first('body') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <button type="submit" class="btn btn-outline-primary btn-lg">{{ $buttonText }}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<section id="questions">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>Ask Question</h2>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Back to Questions Index</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="post">
                           @include("questions._form", ['buttonText' => "Ask Question"])
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<section id="questions">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>Edit Question</h2>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Back to Questions Index</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('questions.update', $question->id) }}" method="post">
                            {{ method_field('PUT') }}
                            @include("questions._form", ['buttonText' => "Update Question"])
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<section id="questions">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>All Questions</h2>
                            <div class="ml-auto">
                                <a href="{{ route('questions.create') }}" class="btn btn-outline-secondary">Ask Question</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        @include ('layouts\_messages')
                        @foreach ($questions as $question)
                        <div class="media mb-4 single-question">
                            <div class="d-flex flex-column counters">
                                <div class="vote">
                                    <strong>{{ $question->votes_count }}</strong> {{ str_plural('vote', $question->votes_count) }}
                                </div>
                                <div class="status {{ $question->status }}">
                                    <strong>{{ $question->answers_count }}</strong> {{ str_plural('answer', $question->votes_count) }}
                                </div>
                                <div class="view">
                                    <strong>{{ $question->views }}</strong> {{ str_plural('view', $question->views) }}
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="d-flex align-items-center">
                                    <h3 class="mt-0 title"><a href="{{ $question->url }}">{{ $question->title }}</a></h3>
                                    <div class="ml-auto">
                                        @can ('update', $question)
                                            <a href="{{ route('questions.edit', $question->id) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                        @endcan

                                        @can ('delete', $question)
                                            <form class="form-delete" method="post" action="{{ route('questions.destroy', $question->id) }}">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</button>
                                            </form>
                                        @endcan
                                    </div>
                                </div>
                                <p class="lead">
                                    Asked by 
                                    <a href="{{ $question->user->url }}">{{ $question->user->name }}</a>
                                    <small class="text-muted">{{ $question->created_date }}</small>
                                </p>
                                <div class="excerpt">{{ $question->excerpt(200) }}</div>
                            </div>
                        </div>
                        @endforeach

                        <div class="text-center">
                            {{ $questions->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<section id="questions">
    <div class="container">
        
        <question-page :question="{{ $question }}"></question-page>

       {{--  @include ('answers._index', [
            'answers'           => $question->answers,
            'answersCount'      => $question->answers_count,
        ]) --}}


        {{-- @include ('answers._create', []) --}}
    </div>
</section>
@endsection